version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/AutoComplete

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-

      - run: cat /dev/null | sbt compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}

      - run: cat /dev/null | sbt test:test
      - run: cat /dev/null | sbt coverageReport
      - codecov/upload:
          file: ./target/scala-2.13/coverage-report/*.xml

      - codecov/upload:
        file: ./target/scala-2.13/resolution-cache/*.xml
      - codecov/upload:
        file: ./target/scala-2.13/scoverage-report/*.xml